
plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
}


dependencies {
    implementation gradleApi()
    implementation localGroovy()
    // ASM依赖
    implementation 'org.ow2.asm:asm:7.0' // 3.6.4兼容的ASM版本
    implementation 'org.ow2.asm:asm-commons:7.0'
    implementation 'commons-io:commons-io:2.6'
    // 适配3.6.4的Android Gradle插件
    implementation 'com.android.tools.build:gradle:3.3.3'

}

//配置正式或者测试服务器,默认上传到测试服务器
def isDev = true
def verPrefix = "1.0.0"
def repoUrl = isDev ? "http://s3.qbuild.corp.qihoo.net:8360/nexus/content/repositories/mobilesafe_platform_snpashot/" : "http://s3.qbuild.corp.qihoo.net:8360/nexus/content/repositories/mobilesafe_platform/"
def ver = isDev ? "${verPrefix}-SNAPSHOT" : "$verPrefix"


publishing {
    publications {
        NetMonitorPlugin(MavenPublication) {
            groupId = 'com.qihoo.net.monitor'
            artifactId = 'net_monitor_plugin'
            version = ver
            // 组件类型，我们的插件其实就是Java组件
            from components.java
        }
    }

    repositories {
        maven {
            mavenLocal()
        }
        mavenLocal()
        // 远程Maven仓库（替换为你的仓库信息）
        maven {
            url = uri(repoUrl) // 仓库URL
            credentials {
                username = '' // 用户名
                password = '' // 密码
            }
        }
    }
}

