
plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
}


dependencies {
    implementation gradleApi()
    implementation localGroovy()
    // ASM依赖
    implementation 'org.ow2.asm:asm:9.1' // 3.6.4兼容的ASM版本
    implementation 'org.ow2.asm:asm-commons:9.1'
    // 适配3.6.4的Android Gradle插件
    implementation 'com.android.tools.build:gradle:3.6.4'

    api 'com.squareup.okhttp3:okhttp:3.10.0'
}

publishing {
    publications {
        // 这里的 hello 可以任意命名
        NetMonitorPlugin(MavenPublication) {
            groupId = 'com.qihoo.net.monitor.plugin'
            artifactId = 'net_monitor_plugin'
            version = '1.0.0'
            // 组件类型，我们的插件其实就是Java组件
            from components.java
        }
    }

    repositories {
        maven {
            mavenLocal()
        }
        mavenLocal()
        // 远程Maven仓库（替换为你的仓库信息）
        maven {
            url = uri('https://your-maven-repo-url') // 仓库URL
            credentials {
                username = 'your-username' // 用户名
                password = 'your-password' // 密码
            }
        }
    }
}

